#!/usr/bin/env bash
# DAT-MODULE
# Id: reports
# Name: Reports
# Description: Generate HTML hardware, network and diagnostic reports
# Entry: module_reports_main
#
# modules/60-reports.sh - HTML reporting (roadmap phase 8).
#
# Reports reuse the read-only collector functions from the system and network
# modules instead of duplicating them. Those module files only define
# functions when sourced, so pulling them in here is safe.

# _reports_load_collectors - Source the system and network modules so their
# sys_* / net_* collector functions are available. Idempotent.
_reports_load_collectors() {
    if ! declare -F sys_os >/dev/null; then
        # shellcheck source=./10-system.sh
        source "${DAT_ROOT}/modules/10-system.sh"
    fi
    if ! declare -F net_ip >/dev/null; then
        # shellcheck source=./20-network.sh
        source "${DAT_ROOT}/modules/20-network.sh"
    fi
}

# --- HTML helpers -------------------------------------------------------------

# html_escape - Escape stdin for safe inclusion in HTML text.
html_escape() {
    sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

# _html_head <title> - Print the document head and opening body with CSS.
_html_head() {
    local title="$1"
    cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 60rem;
         padding: 0 1rem; line-height: 1.5; }
  h1 { border-bottom: 2px solid #888; padding-bottom: .3rem; }
  h2 { margin-top: 2rem; border-bottom: 1px solid #ccc; }
  .meta { color: #666; font-size: .9rem; }
  pre { background: #f4f4f4; color: #111; padding: 1rem; border-radius: 6px;
        overflow-x: auto; white-space: pre-wrap; word-break: break-word; }
  @media (prefers-color-scheme: dark) {
    pre { background: #1e1e1e; color: #e0e0e0; }
  }
  footer { margin-top: 3rem; color: #888; font-size: .85rem; }
</style>
</head>
<body>
EOF
}

# _html_section <heading> <collector> - Emit one <h2> section whose body is
# the escaped output of the collector function.
_html_section() {
    local heading="$1"
    local collector="$2"

    printf '<h2>%s</h2>\n<pre>' "${heading}"
    "${collector}" 2>&1 | html_escape
    printf '</pre>\n'
}

# _html_foot - Print the closing footer and body.
_html_foot() {
    cat <<EOF
<footer>Generated by ${DAT_NAME} $(dat_version) on $(date '+%Y-%m-%d %H:%M:%S')</footer>
</body>
</html>
EOF
}

# --- Report builders ----------------------------------------------------------

# _report_hardware - Full hardware inventory HTML to stdout.
_report_hardware() {
    _html_head "Hardware inventory - $(hostname)"
    printf '<h1>Hardware inventory</h1>\n'
    printf '<p class="meta">Host: %s &middot; %s</p>\n' "$(hostname)" "$(date)"
    _html_section "Operating system" sys_os
    _html_section "Kernel" sys_kernel
    _html_section "CPU" sys_cpu
    _html_section "Memory" sys_memory
    _html_section "BIOS / Mainboard" sys_bios
    _html_section "Temperatures" sys_temps
    _html_section "Disks and filesystems" sys_disks
    _html_section "SMART health" sys_smart
    _html_foot
}

# _report_network - Full network inventory HTML to stdout.
_report_network() {
    _html_head "Network inventory - $(hostname)"
    printf '<h1>Network inventory</h1>\n'
    printf '<p class="meta">Host: %s &middot; %s</p>\n' "$(hostname)" "$(date)"
    _html_section "IP addresses and interfaces" net_ip
    _html_section "Gateway and routing" net_gateway
    _html_section "DNS / resolver" net_dns
    _html_section "Firewall" net_firewall
    _html_section "SSH server" net_ssh
    _html_section "Listening ports" net_ports
    _html_foot
}

# _report_diagnostic - Combined hardware + network diagnostic HTML to stdout.
_report_diagnostic() {
    _html_head "Diagnostic report - $(hostname)"
    printf '<h1>Diagnostic report</h1>\n'
    printf '<p class="meta">Host: %s &middot; %s</p>\n' "$(hostname)" "$(date)"
    printf '<h2 style="border:0">System</h2>\n'
    _html_section "Operating system" sys_os
    _html_section "Kernel" sys_kernel
    _html_section "CPU" sys_cpu
    _html_section "Memory" sys_memory
    _html_section "Temperatures" sys_temps
    _html_section "Disks and filesystems" sys_disks
    _html_section "SMART health" sys_smart
    printf '<h2 style="border:0">Network</h2>\n'
    _html_section "IP addresses and interfaces" net_ip
    _html_section "Gateway and routing" net_gateway
    _html_section "DNS / resolver" net_dns
    _html_section "Firewall" net_firewall
    _html_section "Listening ports" net_ports
    _html_foot
}

# --- Generation flow ----------------------------------------------------------

# _reports_generate <label> <builder> - Ask for a destination, build the
# report and offer to open it.
_reports_generate() {
    local label="$1"
    local builder="$2"

    _reports_load_collectors

    local default_dir="${HOME}/dat-reports"
    local dest
    dest="$(ui_input "${label}" "Directory to save the report in:" "${default_dir}")" || return 0
    [[ -z "${dest}" ]] && dest="${default_dir}"

    if ! mkdir -p "${dest}" 2>/dev/null; then
        ui_msgbox "${label}" "Cannot create directory: ${dest}"
        return 0
    fi

    local slug file
    slug="$(printf '%s' "${label}" | tr '[:upper:] ' '[:lower:]-')"
    file="${dest}/${slug}-$(hostname)-$(date +%Y%m%d-%H%M%S).html"

    log_info "Generating ${label} -> ${file}"
    if "${builder}" > "${file}" 2>/dev/null; then
        ui_msgbox "${label}" "Report written to:
${file}

Open it in a browser to view the formatted report."
    else
        ui_msgbox "${label}" "Failed to generate the report at ${file}."
    fi
}

# module_reports_main - Entry point: choose a report to generate.
module_reports_main() {
    local choice

    while true; do
        if ! choice="$(ui_menu "Reports" "Select a report to generate:" \
            "hardware"   "Hardware inventory (HTML)" \
            "network"    "Network inventory (HTML)" \
            "diagnostic" "Full diagnostic report (HTML)" \
            "back"       "Back to main menu")"; then
            return 0
        fi

        case "${choice}" in
            hardware)   _reports_generate "Hardware inventory" _report_hardware ;;
            network)    _reports_generate "Network inventory" _report_network ;;
            diagnostic) _reports_generate "Diagnostic report" _report_diagnostic ;;
            back)       return 0 ;;
        esac
    done
}
